import { collection, getDocs, setDoc, doc } from "firebase/firestore";
import { db } from "./firebase";

export const sampleDishes = [
  // Asian Cuisine
  {
    id: "sample-1",
    name: "Miso-Glazed Salmon",
    price: 28.99,
    description: "Wild-caught salmon with sweet miso glaze, served with jasmine rice and bok choy.",
    imageUrl: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800",
    images: [
      "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800",
      "https://images.unsplash.com/photo-1485921325833-c519f76c4927?w=800"
    ],
    available: true,
    cuisineType: "Asian",
    dietary: ["Gluten-Free"],
    healthTags: ["High Protein", "Heart Healthy", "Low Sugar"],
    calories: 485,
    protein: 42,
    carbs: 38,
    fat: 18,
    sugar: 6,
    ingredients: ["Wild Salmon", "Miso Paste", "Jasmine Rice", "Bok Choy", "Sesame Oil", "Ginger", "Garlic"],
    tags: ["Asian", "Seafood", "Premium"],
  },
  {
    id: "sample-2",
    name: "Thai Green Curry Bowl",
    price: 22.99,
    description: "Aromatic green curry with vegetables, tofu, and coconut milk over fragrant Thai rice.",
    imageUrl: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800",
    images: ["https://images.unsplash.com/photo-1562565652-a0d8f0c59eb4?w=800"],
    available: true,
    cuisineType: "Asian",
    dietary: ["Vegan", "Gluten-Free"],
    healthTags: ["Low Fat", "High Fiber"],
    calories: 420,
    protein: 18,
    carbs: 52,
    fat: 14,
    sugar: 8,
    ingredients: ["Tofu", "Green Curry Paste", "Coconut Milk", "Thai Basil", "Bamboo Shoots", "Bell Peppers", "Thai Rice"],
    tags: ["Thai", "Spicy", "Plant-Based"],
  },
  {
    id: "sample-3",
    name: "Poke Bowl",
    price: 24.99,
    description: "Fresh ahi tuna poke with edamame, avocado, seaweed salad, and sushi rice.",
    imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800",
    images: ["https://images.unsplash.com/photo-1623587227202-4d0d5a0a3d1f?w=800"],
    available: true,
    cuisineType: "Asian",
    dietary: ["Gluten-Free"],
    healthTags: ["High Protein", "Heart Healthy", "Low Carb"],
    calories: 520,
    protein: 38,
    carbs: 45,
    fat: 20,
    sugar: 4,
    ingredients: ["Ahi Tuna", "Sushi Rice", "Avocado", "Edamame", "Seaweed", "Sesame Seeds", "Soy Sauce"],
    tags: ["Hawaiian", "Raw", "Fresh"],
  },
  
  // Italian Cuisine
  {
    id: "sample-4",
    name: "Truffle Mushroom Risotto",
    price: 32.99,
    description: "Creamy arborio rice with wild mushrooms, parmesan, and black truffle oil.",
    imageUrl: "https://images.unsplash.com/photo-1476124369491-a5bf9d9f821a?w=800",
    images: ["https://images.unsplash.com/photo-1637806930600-37fa8892069d?w=800"],
    available: true,
    cuisineType: "Italian",
    dietary: ["Vegetarian", "Gluten-Free"],
    healthTags: [],
    calories: 680,
    protein: 22,
    carbs: 78,
    fat: 32,
    sugar: 3,
    ingredients: ["Arborio Rice", "Porcini Mushrooms", "Shiitake", "Parmesan", "White Wine", "Black Truffle Oil", "Butter"],
    tags: ["Italian", "Luxury", "Premium"],
  },
  {
    id: "sample-5",
    name: "Margherita Flatbread",
    price: 18.99,
    description: "Classic Neapolitan pizza with San Marzano tomatoes, fresh mozzarella, and basil.",
    imageUrl: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800",
    images: ["https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800"],
    available: true,
    cuisineType: "Italian",
    dietary: ["Vegetarian"],
    healthTags: [],
    calories: 580,
    protein: 26,
    carbs: 65,
    fat: 24,
    sugar: 5,
    ingredients: ["Pizza Dough", "San Marzano Tomatoes", "Fresh Mozzarella", "Basil", "Olive Oil", "Sea Salt"],
    tags: ["Italian", "Classic", "Wood-Fired"],
  },
  {
    id: "sample-6",
    name: "Lobster Linguine",
    price: 42.99,
    description: "Fresh Maine lobster with linguine in white wine garlic sauce and cherry tomatoes.",
    imageUrl: "https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=800",
    images: ["https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800"],
    available: true,
    cuisineType: "Italian",
    dietary: [],
    healthTags: ["High Protein"],
    calories: 720,
    protein: 45,
    carbs: 68,
    fat: 28,
    sugar: 4,
    ingredients: ["Maine Lobster", "Linguine", "Cherry Tomatoes", "White Wine", "Garlic", "Parsley", "Olive Oil"],
    tags: ["Seafood", "Premium", "Luxury"],
  },
  
  // Continental
  {
    id: "sample-7",
    name: "Grilled Ribeye Steak",
    price: 48.99,
    description: "12oz prime ribeye with herb butter, roasted vegetables, and truffle mashed potatoes.",
    imageUrl: "https://images.unsplash.com/photo-1558030006-450675393462?w=800",
    images: ["https://images.unsplash.com/photo-1546833998-877b37c2e5c6?w=800"],
    available: true,
    cuisineType: "American",
    dietary: ["Gluten-Free"],
    healthTags: ["High Protein"],
    calories: 850,
    protein: 62,
    carbs: 35,
    fat: 52,
    sugar: 3,
    ingredients: ["Prime Ribeye", "Herb Butter", "Yukon Potatoes", "Asparagus", "Carrots", "Truffle Oil"],
    tags: ["Steakhouse", "Premium", "Grilled"],
  },
  {
    id: "sample-8",
    name: "Pan-Seared Sea Bass",
    price: 38.99,
    description: "Chilean sea bass with lemon beurre blanc, roasted fingerling potatoes, and broccolini.",
    imageUrl: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800",
    images: ["https://images.unsplash.com/photo-1535140728325-a4d3707eee61?w=800"],
    available: true,
    cuisineType: "French",
    dietary: ["Gluten-Free"],
    healthTags: ["High Protein", "Heart Healthy", "Low Carb"],
    calories: 520,
    protein: 48,
    carbs: 28,
    fat: 24,
    sugar: 2,
    ingredients: ["Chilean Sea Bass", "Lemon", "Butter", "White Wine", "Fingerling Potatoes", "Broccolini"],
    tags: ["Seafood", "French", "Elegant"],
  },
  {
    id: "sample-9",
    name: "Herb-Crusted Rack of Lamb",
    price: 52.99,
    description: "New Zealand lamb with Dijon mustard crust, rosemary jus, and seasonal vegetables.",
    imageUrl: "https://images.unsplash.com/photo-1594041680534-e8c8cdebd659?w=800",
    images: ["https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=800"],
    available: true,
    cuisineType: "French",
    dietary: ["Gluten-Free"],
    healthTags: ["High Protein"],
    calories: 680,
    protein: 54,
    carbs: 22,
    fat: 42,
    sugar: 4,
    ingredients: ["New Zealand Lamb", "Dijon Mustard", "Fresh Herbs", "Breadcrumbs", "Rosemary", "Red Wine", "Root Vegetables"],
    tags: ["Premium", "French", "Sophisticated"],
  },
  
  // Healthy Bowls
  {
    id: "sample-10",
    name: "Quinoa Power Bowl",
    price: 19.99,
    description: "Loaded with quinoa, chickpeas, kale, roasted sweet potato, and tahini dressing.",
    imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800",
    images: ["https://images.unsplash.com/photo-1623428187969-5da2dcea5ebf?w=800"],
    available: true,
    cuisineType: "Mediterranean",
    dietary: ["Vegan", "Gluten-Free"],
    healthTags: ["High Fiber", "Low Fat", "Heart Healthy", "High Protein"],
    calories: 520,
    protein: 22,
    carbs: 72,
    fat: 16,
    sugar: 8,
    ingredients: ["Quinoa", "Chickpeas", "Kale", "Sweet Potato", "Tahini", "Lemon", "Olive Oil"],
    tags: ["Healthy", "Plant-Based", "Superfood"],
  },
  {
    id: "sample-11",
    name: "Grilled Chicken Buddha Bowl",
    price: 21.99,
    description: "Grilled chicken breast with brown rice, avocado, edamame, and ginger-miso dressing.",
    imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800",
    images: ["https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800"],
    available: true,
    cuisineType: "Asian",
    dietary: ["Gluten-Free"],
    healthTags: ["High Protein", "Low Sugar", "Heart Healthy"],
    calories: 480,
    protein: 42,
    carbs: 48,
    fat: 14,
    sugar: 3,
    ingredients: ["Chicken Breast", "Brown Rice", "Avocado", "Edamame", "Carrots", "Cucumber", "Ginger-Miso Dressing"],
    tags: ["Healthy", "Balanced", "Fresh"],
  },
  {
    id: "sample-12",
    name: "Mediterranean Mezze Platter",
    price: 24.99,
    description: "Hummus, baba ganoush, falafel, tabbouleh, olives, and warm pita bread.",
    imageUrl: "https://images.unsplash.com/photo-1529059997568-3d847b1154f0?w=800",
    images: ["https://images.unsplash.com/photo-1593252719532-1e0b3e7e9c95?w=800"],
    available: true,
    cuisineType: "Mediterranean",
    dietary: ["Vegan"],
    healthTags: ["High Fiber", "Heart Healthy"],
    calories: 620,
    protein: 24,
    carbs: 82,
    fat: 24,
    sugar: 6,
    ingredients: ["Chickpeas", "Eggplant", "Tahini", "Parsley", "Bulgur", "Olives", "Pita Bread", "Olive Oil"],
    tags: ["Mediterranean", "Sharing", "Plant-Based"],
  },
  
  // Salads & Light
  {
    id: "sample-13",
    name: "Caesar Salad with Grilled Shrimp",
    price: 22.99,
    description: "Crisp romaine with parmesan, house-made croutons, and jumbo grilled shrimp.",
    imageUrl: "https://images.unsplash.com/photo-1546793665-c74683f339c1?w=800",
    images: ["https://images.unsplash.com/photo-1512852939750-1305098529bf?w=800"],
    available: true,
    cuisineType: "American",
    dietary: [],
    healthTags: ["High Protein", "Low Carb"],
    calories: 420,
    protein: 38,
    carbs: 24,
    fat: 22,
    sugar: 2,
    ingredients: ["Romaine Lettuce", "Jumbo Shrimp", "Parmesan", "Caesar Dressing", "Croutons", "Lemon"],
    tags: ["Salad", "Classic", "Fresh"],
  },
  {
    id: "sample-14",
    name: "Avocado Chicken Salad",
    price: 19.99,
    description: "Mixed greens with grilled chicken, avocado, cherry tomatoes, and citrus vinaigrette.",
    imageUrl: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800",
    images: ["https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800"],
    available: true,
    cuisineType: "American",
    dietary: ["Keto", "Gluten-Free"],
    healthTags: ["Low Sugar", "Low Carb", "High Protein", "Heart Healthy"],
    calories: 380,
    protein: 34,
    carbs: 18,
    fat: 22,
    sugar: 4,
    ingredients: ["Mixed Greens", "Grilled Chicken", "Avocado", "Cherry Tomatoes", "Red Onion", "Citrus Vinaigrette"],
    tags: ["Salad", "Keto", "Fresh"],
  },
  
  // Burgers & Sandwiches
  {
    id: "sample-15",
    name: "Wagyu Beef Burger",
    price: 26.99,
    description: "Premium wagyu patty with aged cheddar, caramelized onions, and truffle aioli on brioche.",
    imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800",
    images: ["https://images.unsplash.com/photo-1550547660-d9450f859349?w=800"],
    available: true,
    cuisineType: "American",
    dietary: [],
    healthTags: ["High Protein"],
    calories: 820,
    protein: 48,
    carbs: 52,
    fat: 48,
    sugar: 8,
    ingredients: ["Wagyu Beef", "Aged Cheddar", "Brioche Bun", "Caramelized Onions", "Truffle Aioli", "Arugula"],
    tags: ["Burger", "Premium", "Comfort Food"],
  },
  {
    id: "sample-16",
    name: "Grilled Portobello Burger",
    price: 18.99,
    description: "Marinated portobello mushroom with roasted red peppers, arugula, and balsamic glaze.",
    imageUrl: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800",
    images: ["https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=800"],
    available: true,
    cuisineType: "American",
    dietary: ["Vegan"],
    healthTags: ["Low Fat", "Low Sugar", "High Fiber"],
    calories: 420,
    protein: 14,
    carbs: 58,
    fat: 16,
    sugar: 12,
    ingredients: ["Portobello Mushroom", "Whole Wheat Bun", "Roasted Red Peppers", "Arugula", "Balsamic Glaze", "Olive Oil"],
    tags: ["Vegan", "Burger", "Plant-Based"],
  },
  
  // Desserts
  {
    id: "sample-17",
    name: "Chocolate Lava Cake",
    price: 14.99,
    description: "Warm chocolate cake with molten center, served with vanilla bean ice cream.",
    imageUrl: "https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=800",
    images: ["https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=800"],
    available: true,
    cuisineType: "Dessert",
    dietary: ["Vegetarian"],
    healthTags: [],
    calories: 620,
    protein: 8,
    carbs: 68,
    fat: 36,
    sugar: 48,
    ingredients: ["Dark Chocolate", "Butter", "Eggs", "Sugar", "Flour", "Vanilla Ice Cream"],
    tags: ["Dessert", "Chocolate", "Indulgent"],
  },
  {
    id: "sample-18",
    name: "New York Cheesecake",
    price: 12.99,
    description: "Classic creamy cheesecake with graham cracker crust and berry compote.",
    imageUrl: "https://images.unsplash.com/photo-1533134242148-b4d2e8d4e99c?w=800",
    images: ["https://images.unsplash.com/photo-1524351199678-941a58a3df50?w=800"],
    available: true,
    cuisineType: "Dessert",
    dietary: ["Vegetarian"],
    healthTags: [],
    calories: 580,
    protein: 10,
    carbs: 52,
    fat: 38,
    sugar: 42,
    ingredients: ["Cream Cheese", "Graham Crackers", "Butter", "Sugar", "Eggs", "Mixed Berries", "Vanilla"],
    tags: ["Dessert", "Classic", "Creamy"],
  },
  {
    id: "sample-19",
    name: "Tiramisu",
    price: 13.99,
    description: "Traditional Italian dessert with espresso-soaked ladyfingers and mascarpone cream.",
    imageUrl: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=800",
    images: ["https://images.unsplash.com/photo-1534760177226-a6ca97c1d2f7?w=800"],
    available: true,
    cuisineType: "Dessert",
    dietary: ["Vegetarian"],
    healthTags: [],
    calories: 520,
    protein: 9,
    carbs: 48,
    fat: 32,
    sugar: 38,
    ingredients: ["Ladyfingers", "Espresso", "Mascarpone", "Eggs", "Sugar", "Cocoa Powder", "Marsala Wine"],
    tags: ["Dessert", "Italian", "Coffee"],
  },
  {
    id: "sample-20",
    name: "Açaí Superfood Bowl",
    price: 16.99,
    description: "Organic açaí blend topped with granola, fresh berries, banana, and honey drizzle.",
    imageUrl: "https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800",
    images: ["https://images.unsplash.com/photo-1511067960412-0436d00bb75e?w=800"],
    available: true,
    cuisineType: "Healthy",
    dietary: ["Vegan", "Gluten-Free"],
    healthTags: ["High Fiber", "Low Fat", "Heart Healthy"],
    calories: 380,
    protein: 8,
    carbs: 62,
    fat: 12,
    sugar: 32,
    ingredients: ["Açaí Berries", "Banana", "Granola", "Strawberries", "Blueberries", "Honey", "Coconut Flakes"],
    tags: ["Healthy", "Breakfast", "Superfood"],
  },
];

export async function seedSampleDishes() {
  try {
    const menuRef = collection(db, "menu");
    const snapshot = await getDocs(menuRef);
    
    if (snapshot.empty) {
      console.log("Seeding sample menu items...");
      
      for (const dish of sampleDishes) {
        await setDoc(doc(db, "menu", dish.id), dish);
      }
      
      console.log("Sample menu items added successfully!");
      return true;
    } else {
      console.log("Menu already has items, skipping seed.");
      return false;
    }
  } catch (error) {
    console.error("Error seeding sample dishes:", error);
    return false;
  }
}
